import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';import crypto from 'node:crypto';import pg from 'pg';import express from 'express';
import {validateReleaseMetadata,applyReleaseMetadata} from '../src/artists/releaseMetadata.mjs';
const helpers={assertOwnedObjectKey:(user,key)=>{if(!key.startsWith(user+'/'))throw Object.assign(new Error('forbidden'),{statusCode:403});return key;},readObjectMetadata:async key=>({contentType:key.endsWith('.png')?'image/png':'audio/wav'})};
test('release date and record label validate without timezone shifts or fabricated dates',async()=>{
 assert.deepEqual(await validateReleaseMetadata({releaseDate:'2024-02-29',recordLabel:' Label '},'owner',helpers),{releaseDate:'2024-02-29',recordLabel:'Label'});
 for(const releaseDate of ['2023-02-29','2026-04-31','2026-1-2','0000-01-01','invalid'])await assert.rejects(validateReleaseMetadata({releaseDate},'owner',helpers),/invalid_release_date/);
 await assert.rejects(validateReleaseMetadata({recordLabel:'x'.repeat(181)},'owner',helpers),/invalid_record_label/);
 await assert.rejects(validateReleaseMetadata({artworkObjectKey:'other/cover.png'},'owner',helpers),/forbidden/);
 await assert.rejects(validateReleaseMetadata({artworkObjectKey:'owner/audio.wav'},'owner',helpers),/image_file_required/);
 assert.deepEqual(await validateReleaseMetadata({},'owner',helpers),{});
});
test('actual track edit route persists shared release metadata atomically and enforces uploader ownership',{skip:!process.env.TEST_SAAS_DATABASE_URL},async t=>{
 const url=new URL(process.env.TEST_SAAS_DATABASE_URL);if(!['127.0.0.1','localhost'].includes(url.hostname)||url.pathname!=='/ysong_saas_validation')throw Error('Dedicated loopback fixture required');
 const root=new pg.Pool({connectionString:url.href}),schema='metadata_'+crypto.randomUUID().replaceAll('-','');await root.query('CREATE SCHEMA '+schema);const pool=new pg.Pool({connectionString:url.href,options:'-c search_path='+schema});t.after(async()=>{await pool.end();await root.end();});
 await pool.query(`CREATE TABLE world_releases(id uuid PRIMARY KEY,owner_user_id uuid,artist_name text,title text,release_type text,genre text,artwork_object_key text,release_date date,record_label text DEFAULT '');
 CREATE TABLE world_tracks(id uuid PRIMARY KEY,release_id uuid,owner_user_id uuid,artist_id uuid,title text,genre text,tags jsonb DEFAULT '[]',description text DEFAULT '',explicit bool DEFAULT false,track_number int DEFAULT 1,isrc text,previously_released bool DEFAULT false,duration_seconds float,play_count int DEFAULT 7,published_at timestamptz DEFAULT now());
 CREATE TABLE world_track_reactions(track_id uuid,user_id uuid,reaction int);CREATE TABLE world_saved_tracks(track_id uuid,user_id uuid);CREATE TABLE world_saved_releases(release_id uuid,user_id uuid);CREATE TABLE world_followed_artists(user_id uuid,artist_owner_user_id uuid,artist_name text);CREATE TABLE world_track_comments(track_id uuid,is_deleted bool);`);
 const user=crypto.randomUUID(),other=crypto.randomUUID(),release=crypto.randomUUID(),track=crypto.randomUUID(),sibling=crypto.randomUUID();await pool.query("INSERT INTO world_releases VALUES($1,$2,'Artist','Album','album','Rock',$3,NULL,'')",[release,user,user+'/original.png']);await pool.query("INSERT INTO world_tracks(id,release_id,owner_user_id,title,genre) VALUES($1,$2,$3,'Track','Rock'),($4,$2,$3,'Sibling','Rock')",[track,release,user,sibling]);
 await pool.query('ALTER TABLE world_releases ADD COLUMN artist_id uuid; ALTER TABLE world_releases ADD COLUMN created_at timestamptz DEFAULT now(); ALTER TABLE world_tracks ADD COLUMN audio_object_key text; ALTER TABLE world_tracks ADD COLUMN status text; CREATE TABLE artists(id uuid PRIMARY KEY,owner_user_id uuid,name text)');
 const artist=crypto.randomUUID();await pool.query("INSERT INTO artists VALUES($1,$2,'Artist')",[artist,user]);await pool.query('UPDATE world_releases SET artist_id=$1',[artist]);
 const app=express();app.use(express.json());const source=fs.readFileSync(new URL('../src/index.js',import.meta.url),'utf8');const start=source.indexOf('function worldRow('),end=source.indexOf('\n}',start)+2;const routeStart=source.indexOf('app.patch("/api/world/tracks/:id"'),routeEnd=source.indexOf('app.patch("/api/world/releases/:id"',routeStart);
 const context={app,pool,crypto,validateReleaseMetadata,applyReleaseMetadata,...helpers,normalizeIsrc:x=>String(x),validIsrc:()=>true,console:{error:()=>{},warn:()=>{}},assertObjectReadable:async()=>{},governance:{assertPublic:async()=>{}},syncAchievementsForUser:async()=>{},requireAuth:(req,res,next)=>{if(![user,other].includes(req.get('authorization')))return res.sendStatus(401);req.user={id:req.get('authorization')};next();}};vm.runInNewContext(source.slice(start,end)+'\n'+source.slice(routeStart,routeEnd),context);const publishStart=source.indexOf('app.post("/api/world/publish"'),publishEnd=source.indexOf('app.get("/api/world/tracks"',publishStart);vm.runInNewContext(source.slice(publishStart,publishEnd),context);
 const server=app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));t.after(()=>new Promise(r=>server.close(r)));const request=async(body,uid=user)=>{const r=await fetch('http://127.0.0.1:'+server.address().port+'/api/world/tracks/'+track,{method:'PATCH',headers:{authorization:uid,'content-type':'application/json'},body:JSON.stringify(body)});return{status:r.status,data:await r.json()};};
 await t.test('date/label/cover round-trip while IDs, upload time, sibling and plays survive',async()=>{
  const before=(await pool.query('SELECT published_at FROM world_tracks WHERE id=$1',[track])).rows[0].published_at;const r=await request({title:'Updated',releaseDate:'2024-02-29',recordLabel:'My Records',artworkObjectKey:user+'/new.png'});assert.equal(r.status,200);assert.equal(r.data.track.releaseDate,'2024-02-29');assert.equal(r.data.track.recordLabel,'My Records');assert.ok(r.data.track.artworkVersion);assert.equal(r.data.track.id,track);assert.equal(r.data.track.playCount,7);assert.equal(new Date(r.data.track.publishedAt).getTime(),before.getTime());assert.equal((await pool.query('SELECT title FROM world_tracks WHERE id=$1',[sibling])).rows[0].title,'Sibling');
 });
 await t.test('unowned images, other uploaders, invalid dates and non-image objects cannot edit',async()=>{
  assert.equal((await request({releaseDate:'2023-02-29'})).status,400);assert.equal((await request({recordLabel:'Other'},other)).status,404);assert.equal((await request({artworkObjectKey:other+'/new.png'})).status,403);assert.equal((await request({artworkObjectKey:user+'/audio.wav'})).status,400);
 });
 await t.test('track write failure rolls back cover/date/label together',async()=>{
  await pool.query(`CREATE FUNCTION reject_bad_title() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF NEW.title='force-failure' THEN RAISE EXCEPTION 'fixture'; END IF;RETURN NEW; END $$; CREATE TRIGGER bad_title BEFORE UPDATE ON world_tracks FOR EACH ROW EXECUTE FUNCTION reject_bad_title();`);
  assert.equal((await request({title:'force-failure',recordLabel:'Do not persist',releaseDate:'2025-01-01',artworkObjectKey:user+'/failed.png'})).status,500);const r=(await pool.query('SELECT record_label,release_date::text,artwork_object_key FROM world_releases WHERE id=$1',[release])).rows[0];assert.equal(r.record_label,'My Records');assert.equal(r.release_date,'2024-02-29');assert.equal(r.artwork_object_key,user+'/new.png');
 });
 await t.test('omission preserves release fields and explicit clearing handles optional values',async()=>{
  assert.equal((await request({description:'New description'})).data.track.releaseDate,'2024-02-29');const cleared=await request({releaseDate:null,recordLabel:''});assert.equal(cleared.data.track.releaseDate,null);assert.equal(cleared.data.track.recordLabel,'');assert.ok(cleared.data.track.artworkVersion);
 });
 await t.test('an update rejected without an exception cannot commit release metadata',async()=>{
  await pool.query("CREATE FUNCTION skip_title_update() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF NEW.title='skip-update' THEN RETURN NULL; END IF; RETURN NEW; END $$; CREATE TRIGGER skip_update BEFORE UPDATE ON world_tracks FOR EACH ROW EXECUTE FUNCTION skip_title_update();");
  assert.equal((await request({title:'skip-update',recordLabel:'Do not persist'})).status,500);assert.equal((await pool.query('SELECT record_label FROM world_releases WHERE id=$1',[release])).rows[0].record_label,'');
 });
 await t.test('publish saves calendar date and record label for singles and albums; blanks preserve existing album metadata',async()=>{
  const publish=async patch=>{const r=await fetch('http://127.0.0.1:'+server.address().port+'/api/world/publish',{method:'POST',headers:{authorization:user,'content-type':'application/json'},body:JSON.stringify({title:'Upload',artistId:artist,rightsConfirmed:true,audioObjectKey:user+'/audio.wav',...patch})});return{status:r.status,data:await r.json()};};
  const single=await publish({releaseDate:'2020-12-31',recordLabel:' Label '});assert.equal(single.status,201);assert.equal(single.data.track.releaseDate,'2020-12-31');assert.equal(single.data.track.recordLabel,'Label');
  const album=await publish({releaseType:'album',albumTitle:'Album',releaseDate:'2021-06-01',recordLabel:'Album Label'});assert.equal(album.status,201);assert.equal(album.data.releaseId,release);assert.equal(album.data.track.recordLabel,'Album Label');
  const preserved=await publish({releaseType:'album',albumTitle:'Album'});assert.equal(preserved.data.track.releaseDate,'2021-06-01');assert.equal(preserved.data.track.recordLabel,'Album Label');
  const before=Number((await pool.query('SELECT count(*) FROM world_tracks')).rows[0].count);assert.equal((await publish({releaseDate:'2023-02-29'})).status,400);assert.equal((await publish({recordLabel:'x'.repeat(181)})).status,400);assert.equal(Number((await pool.query('SELECT count(*) FROM world_tracks')).rows[0].count),before);
  await pool.query("CREATE FUNCTION reject_upload() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF NEW.title='fail-upload' THEN RAISE EXCEPTION 'fixture'; END IF; RETURN NEW; END $$; CREATE TRIGGER bad_upload BEFORE INSERT ON world_tracks FOR EACH ROW EXECUTE FUNCTION reject_upload();");
  assert.equal((await publish({title:'fail-upload',releaseType:'album',albumTitle:'Album',recordLabel:'Do not persist'})).status,500);assert.equal((await pool.query('SELECT record_label FROM world_releases WHERE id=$1',[release])).rows[0].record_label,'Album Label');
 });
});
