import test from 'node:test';
import assert from 'node:assert/strict';
import crypto from 'node:crypto';
import fs from 'node:fs/promises';
import pg from 'pg';
import express from 'express';
import Stripe from 'stripe';
import {createSaasService} from '../src/saas/service.mjs';
import {stripeAdapter,verifyBillingEvent,applySubscriptionEvent,registerBillingWebhook} from '../src/saas/billing.mjs';
import {registerSaasRoutes} from '../src/saas/routes.mjs';
import {registerRecoveryRoutes} from '../src/saas/recovery.mjs';
import {validateLaunchConfiguration,applyLaunchConfiguration} from '../src/saas/configuration.mjs';
import {environmentGates,catalogGates,readiness} from '../src/saas/preflight.mjs';
import {sessionSource,createSessionJobs} from '../src/saas/jobs.mjs';
const reviewed=admin=>({mode:'test',databaseHost:'localhost',superadminUserId:admin,plans:['free','basic','pro','premium'].map(id=>({id,quota:5,storageQuotaBytes:null,capabilities:{generation:true,assistant:true,uploads:true,artwork:false},assistantLimit:2,available:true,priceId:id==='free'?null:'price_'+id,productId:id==='free'?null:'prod_'+id})),policies:['terms','privacy','upload-rights','billing','generated-output','bridge-license'].map(id=>({id,version:'reviewed-v1',url:'https://www.ysong.ai/legal/'+id+'/v1',approvalReference:'Fixture counsel reference only'}))});
test('billing mode/key separation fails closed without printing credentials',()=>{
 for(const env of [{BILLING_MODE:'live',STRIPE_SECRET_KEY:'sk_test_fixture'},{BILLING_MODE:'test',STRIPE_SECRET_KEY:'sk_live_fixture'},{BILLING_MODE:'invalid',STRIPE_SECRET_KEY:'sk_test_fixture'},{}])assert.throws(()=>stripeAdapter(env),/billing_not_configured/);
 assert.throws(()=>verifyBillingEvent(Buffer.from('{}'),'anything',{BILLING_MODE:'live'}),/billing_not_configured/);
});
test('preflight distinguishes missing configuration, inconsistent mode and SaaS enablement',()=>{
 assert.equal(readiness(environmentGates({})),'NOT CONFIGURED');assert.equal(readiness(environmentGates({BILLING_MODE:'live',STRIPE_SECRET_KEY:'sk_test_fixture'})),'FAIL');assert.equal(readiness(environmentGates({SAAS_ENABLED:'1'})),'FAIL');assert.equal(catalogGates([]).find(g=>g.gate==='Live price/product mappings').status,'NOT CONFIGURED');
});
test('operator configuration rejects placeholders, duplicate mappings and invented unlimited allowances',()=>{
 const c=reviewed(crypto.randomUUID());assert.equal(validateLaunchConfiguration(c).plans.length,4);
 for(const mutate of [c=>c.plans[0].quota=null,c=>c.plans[2].priceId=c.plans[1].priceId,c=>c.policies[0].version='attorney-review-required',c=>c.policies[0].approvalReference='',c=>c.plans[0].assistantLimit=null,c=>c.plans[0].priceId='price_free']){const bad=structuredClone(c);mutate(bad);assert.throws(()=>validateLaunchConfiguration(bad));}
});
test('real launch configuration/recovery/billing boundaries on isolated PostgreSQL',{skip:!process.env.TEST_SAAS_DATABASE_URL},async t=>{
 const url=new URL(process.env.TEST_SAAS_DATABASE_URL);if(!['127.0.0.1','localhost'].includes(url.hostname)||url.pathname!=='/ysong_saas_validation')throw new Error('Dedicated loopback fixture required');
 const schema='readiness_'+crypto.randomUUID().replaceAll('-',''),root=new pg.Pool({connectionString:url.href});await root.query('CREATE SCHEMA '+schema);const pool=new pg.Pool({connectionString:url.href,options:'-c search_path='+schema,max:10});t.after(async()=>{await pool.end();await root.end();});
 await pool.query("CREATE TABLE users(id uuid PRIMARY KEY,email text,display_name text,created_at timestamptz DEFAULT now());CREATE TABLE user_client_state(user_id uuid PRIMARY KEY,state jsonb DEFAULT '{}',updated_at timestamptz DEFAULT now())");
 const admin=crypto.randomUUID(),user=crypto.randomUUID(),old=crypto.randomUUID();await pool.query('INSERT INTO users(id,email) VALUES($1,$2),($3,$4),($5,$6)',[admin,'psychopathetica@gmail.com',user,'fixture@example.invalid',old,'existing@example.invalid']);
 const sql=await fs.readFile(new URL('../src/saas/schema.sql',import.meta.url),'utf8');await pool.query(sql);await pool.query(sql);const service=createSaasService(pool);const config=reviewed(admin);
 await service.transaction(c=>applyLaunchConfiguration(c,config));
 const secret='whsec_fixture_only',env={BILLING_MODE:'test',BILLING_RETURN_URL:'http://localhost/app',BILLING_SUCCESS_URL:'http://localhost/app?billing=success',BILLING_CANCEL_URL:'http://localhost/app?billing=cancelled',STRIPE_PORTAL_CONFIGURATION_ID:'bpc_fixture',STRIPE_WEBHOOK_SECRET:secret,BILLING_WEBHOOK_ENABLED:'1'};
 let checkout=0,retrieval=0,sub={id:'sub_fixture',customer:'cus_fixture',livemode:false,status:'active',current_period_start:100,current_period_end:4102444800,cancel_at_period_end:false,items:{data:[{price:{id:'price_pro',product:'prod_pro'}}]}};
 const stripe={prices:{retrieve:async id=>({active:true,livemode:false,currency:'usd',unit_amount:id==='price_basic'?999:id==='price_pro'?1999:2999,recurring:{interval:'month'},product:'prod_'+id.slice(6)})},subscriptions:{retrieve:async()=>{retrieval++;return sub;}},checkout:{sessions:{create:async()=>{checkout++;return{id:'cs_fixture',url:'https://checkout.stripe.com/fixture'};}}},customers:{create:async()=>({id:'cus_fixture'}),retrieve:async id=>({id,livemode:false,metadata:{ysong_user_id:old}})},billingPortal:{sessions:{create:async body=>{assert.equal(body.configuration,'bpc_fixture');return {url:'https://billing.stripe.com/fixture'};}}},events:{retrieve:async()=>({id:'evt_replay',livemode:false,type:'invoice.payment_failed',created:1000,data:{object:{id:'in_replay',customer:'cus_fixture'}}})}};
 const app=express();registerBillingWebhook(app,express,service,()=>false,env);app.use(express.json());const auth=async(req,res,next)=>{const id=req.get('authorization');if(![admin,user,old].includes(id))return res.sendStatus(401);try{await service.access(id,Math.floor(Date.now()/1000));req.user={id,issuedAt:Math.floor(Date.now()/1000)};next();}catch(e){res.status(e.status??503).json({error:e.code});}};
 const adapter=()=>({stripe,live:false});registerSaasRoutes(app,{pool,service,requireAuth:auth,enabled:()=>true,env,billingAdapter:adapter});registerRecoveryRoutes(app,{pool,service,requireAuth:auth,enabled:()=>true,env,billingAdapter:adapter});
 const liveApp=express();registerSaasRoutes(liveApp,{pool,service,requireAuth:auth,enabled:()=>true,env:{...env,BILLING_MODE:'live',BILLING_RETURN_URL:'https://www.ysong.ai/app',BILLING_SUCCESS_URL:'https://www.ysong.ai/app?billing=success',BILLING_CANCEL_URL:'https://www.ysong.ai/app?billing=cancelled'},billingAdapter:()=>({stripe,live:true})});app.use('/live',liveApp);
 const server=app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));t.after(()=>new Promise(r=>server.close(r)));const base='http://127.0.0.1:'+server.address().port;
 const request=async(path,body,uid=admin)=>{const r=await fetch(base+path,{method:body===undefined?'GET':'POST',headers:{authorization:uid,'content-type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)});return{status:r.status,data:await r.json().catch(()=>null)};};
 await t.test('existing Free accounts initialize once without subscriptions, projects or paid tiers changing',async()=>{
  await pool.query("INSERT INTO user_client_state(user_id,state) VALUES($1,'{\"ysong:daw:existing\":\"saved project\"}')",[old]);const e=await service.summary(old);assert.equal(e.planId,'free');assert.equal(e.status,'active');assert.equal(e.used,0);assert.equal((await pool.query('SELECT billing_subscription_id FROM ysong_account_access WHERE user_id=$1',[old])).rows[0].billing_subscription_id,null);await pool.query(sql);assert.equal((await pool.query('SELECT state FROM user_client_state WHERE user_id=$1',[old])).rows[0].state['ysong:daw:existing'],'saved project');assert.equal((await service.summary(old)).planId,'free');
 });
 await t.test('approved version configuration is replayable, immutable and rejects stale approval changes',async()=>{
  await service.transaction(c=>applyLaunchConfiguration(c,config));assert.equal((await pool.query('SELECT * FROM ysong_policy_versions WHERE active')).rows.length,6);
  const changed=structuredClone(config);changed.policies[0].url='https://www.ysong.ai/changed';await assert.rejects(service.transaction(c=>applyLaunchConfiguration(c,changed)),/immutable/);assert.equal((await pool.query("SELECT url FROM ysong_policy_versions WHERE policy_id='terms' AND active")).rows[0].url,config.policies[0].url);
 });
 await t.test('missing/invalid catalog mappings prevent Checkout; portal selects the configured portal',async()=>{
  await pool.query('INSERT INTO ysong_policy_acceptances(user_id,policy_id,version) SELECT $1,policy_id,version FROM ysong_policy_versions WHERE active',[user]);
  await pool.query("UPDATE ysong_plans SET billing_prices='{}' WHERE id='basic'");assert.equal((await request('/api/billing/checkout',{planId:'basic',requestKey:'missing-price'},user)).status,503);
  await pool.query("UPDATE ysong_plans SET billing_prices='{\"stripe:test\":\"price_basic\"}',billing_products='{\"stripe:test\":\"prod_wrong\"}' WHERE id='basic'");assert.equal((await request('/api/billing/checkout',{planId:'basic',requestKey:'wrong-product'},user)).status,503);assert.equal(checkout,0);
  assert.equal((await request('/live/api/billing/checkout',{planId:'basic',requestKey:'missing-live-price'},user)).status,503);
  await pool.query("UPDATE ysong_plans SET billing_prices=billing_prices||'{\"stripe:live\":\"price_basic\"}' WHERE id='basic'");assert.equal((await request('/live/api/billing/checkout',{planId:'basic',requestKey:'missing-live-product'},user)).data.error,'billing_product_not_configured');
  await pool.query("UPDATE ysong_plans SET billing_products=billing_products||'{\"stripe:live\":\"prod_basic\"}' WHERE id='basic'");assert.equal((await request('/live/api/billing/checkout',{planId:'basic',requestKey:'wrong-live-mode'},user)).data.error,'billing_price_catalog_mismatch');assert.equal(checkout,0);
  await service.transaction(c=>applyLaunchConfiguration(c,config));await pool.query("UPDATE ysong_account_access SET billing_provider='stripe',billing_live=false,billing_customer_id='cus_fixture',billing_subscription_id='sub_fixture' WHERE user_id=$1",[user]);assert.equal((await request('/api/billing/portal',{},user)).status,200);
 });
 await t.test('subscription transitions, downgrade/upgrade timing, stale ordering and superadmin billing immunity',async()=>{
  let time=100;for(const status of ['incomplete','past_due','active','unpaid','trialing','canceled']){const s={...sub,status};await applySubscriptionEvent(service,{id:'evt_'+status,type:status==='canceled'?'customer.subscription.deleted':'customer.subscription.updated',created:time++,livemode:false},s);assert.equal((await service.summary(user)).planId,['active','trialing'].includes(status)?'pro':'free');}
  await applySubscriptionEvent(service,{id:'evt_upgrade',type:'customer.subscription.updated',created:200,livemode:false},sub);assert.equal((await service.summary(user)).planId,'pro');
  await applySubscriptionEvent(service,{id:'evt_downgrade',type:'customer.subscription.updated',created:300,livemode:false},{...sub,items:{data:[{price:{id:'price_basic',product:'prod_basic'}}]}});assert.equal((await service.summary(user)).planId,'basic');
  await applySubscriptionEvent(service,{id:'evt_stale',type:'customer.subscription.updated',created:250,livemode:false},sub);assert.equal((await service.summary(user)).planId,'basic');
  await pool.query("UPDATE ysong_account_access SET billing_provider='stripe',billing_live=false,billing_customer_id='cus_admin' WHERE user_id=$1",[admin]);await applySubscriptionEvent(service,{id:'evt_admin_cancel',type:'customer.subscription.deleted',created:400,livemode:false},{...sub,id:'sub_admin',customer:'cus_admin',status:'canceled'});assert.equal((await service.summary(admin)).superadmin,true);assert.equal((await service.summary(admin)).quota,null);
 });
 await t.test('audited billing reconciliation is read-only at Stripe, owner/mode checked and idempotent',async()=>{
  const path='/api/admin/recovery/billing/'+user+'/reconcile',body={requestKey:'recovery-fixture',reason:'Verified current Stripe state after delivery outage'};
  assert.equal((await request(path,body,user)).status,403);assert.equal((await request(path,body)).status,200);assert.equal((await service.summary(user)).planId,'pro');assert.equal((await request(path,body)).data.duplicate,true);assert.equal(retrieval,2);assert.equal((await pool.query("SELECT * FROM ysong_admin_audit WHERE action='billing_reconciliation'")).rows.length,1);
  sub={...sub,livemode:true};assert.equal((await request(path,{...body,requestKey:'wrong-mode-recovery'})).status,409);sub={...sub,livemode:false};assert.equal(checkout,0);
 });
 await t.test('verified invoice notifications and failed webhook replay do not grant access or spam',async()=>{
  const payload=JSON.stringify({id:'evt_invoice',type:'invoice.paid',livemode:false,created:500,data:{object:{id:'in_fixture',customer:'cus_fixture'}}});const signature=Stripe.webhooks.generateTestHeaderString({payload,secret});
  const send=()=>fetch(base+'/api/billing/webhook',{method:'POST',headers:{'content-type':'application/json','stripe-signature':signature},body:payload});assert.equal((await send()).status,200);assert.equal((await send()).status,200);assert.equal((await pool.query("SELECT * FROM ysong_notifications WHERE entity_id='billing:evt_invoice'")).rows.length,1);
  await pool.query("INSERT INTO ysong_billing_failures(live,event_id,event_type,error_code) VALUES(false,'evt_replay','invoice.payment_failed','billing_temporarily_unavailable')");const path='/api/admin/recovery/billing-events/evt_replay/replay',body={reason:'Verified event after transient database failure'};assert.equal((await request(path,body)).status,200);assert.equal((await request(path,body)).data.duplicate,true);assert.equal((await pool.query("SELECT * FROM ysong_notifications WHERE entity_id='billing:evt_replay'")).rows.length,1);assert.equal((await service.summary(user)).planId,'pro');
 });
 await t.test('active standalone executor blocks review; stopped submission becomes reviewable without refund',async()=>{
  const r=await service.reserve(user,{quantity:1,requestKey:'stranded-standalone',source:{instructions:'fixture'}}),id=r.versions[0].id;await service.start(id,'cloudflare','minimax/music-2.6');await pool.query("UPDATE ysong_generation_versions SET execution='{\"parts\":{\"audio\":{\"state\":\"submitted\"}},\"saved\":false}' WHERE id=$1",[id]);const release=await service.acquireRender(id);const path='/api/admin/recovery/generations/'+id+'/review-submission',body={reason:'Old executor stopped; outcome needs provider evidence'};
  assert.equal((await request(path,body)).status,409);await release();assert.equal((await request(path,body,user)).status,403);assert.equal((await request(path,body)).status,200);assert.equal((await request(path,body)).data.duplicate,true);assert.equal((await service.summary(user)).reserved,1);assert.equal((await pool.query('SELECT execution FROM ysong_generation_versions WHERE id=$1',[id])).rows[0].execution.parts.audio.state,'ambiguous');
 });
 await t.test('unsubmitted cancellation and reservation recount preserve used units and audit once',async()=>{
  const r=await service.reserve(user,{quantity:1,requestKey:'admin-cancel-queued',source:{instructions:'fixture'}}),path='/api/admin/recovery/generations/'+r.versions[0].id+'/cancel-queued',body={reason:'Owner requested unsubmitted queued cancellation'};assert.equal((await request(path,body)).status,200);assert.equal((await request(path,body)).data.duplicate,true);assert.equal((await service.summary(user)).reserved,1);
  const p=(await pool.query('SELECT * FROM ysong_quota_periods WHERE user_id=$1',[user])).rows[0];await pool.query('UPDATE ysong_quota_periods SET reserved=3 WHERE id=$1',[p.id]);const recount='/api/admin/recovery/quota/'+p.id+'/recount-reservations';assert.equal((await request(recount,{reason:'Compare retained version ledger after storage outage',expectedReserved:2})).status,409);assert.equal((await request(recount,{reason:'Compare retained version ledger after storage outage',expectedReserved:3})).data.reserved,1);assert.equal((await request(recount,{reason:'Replay verified recount after response interruption',expectedReserved:3})).data.duplicate,true);assert.equal((await service.summary(user)).used,p.used);
 });
 await t.test('manual notice delivery requires evidence/current case and never claims to send email',async()=>{
  const key='user-uploads/'+user+'/case.wav',id=crypto.randomUUID();await pool.query("INSERT INTO ysong_content_reviews VALUES($1,$2,'hash','removed','{}',NULL,now())",[key,user]);await pool.query("INSERT INTO ysong_takedown_cases(id,claimant_user_id,object_key,contact_reference,claim) VALUES($1,$2,$3,'fixture','Fixture legal claim')",[id,user,key]);const before=(await pool.query('SELECT * FROM ysong_takedown_cases WHERE id=$1',[id])).rows[0];const body={reason:'Human delivery receipt recorded after legal review',status:'delivered',reference:'receipt-fixture',expectedUpdatedAt:before.updated_at.toISOString()},path='/api/admin/recovery/takedowns/'+id+'/notification';
  assert.equal((await request(path,{...body,reference:''})).status,400);assert.equal((await request(path,{...body,expectedUpdatedAt:'2000-01-01'})).status,409);assert.equal((await request(path,body,user)).status,403);assert.equal((await request(path,body)).status,200);assert.equal((await request(path,body)).data.duplicate,true);
 });
 await t.test('incomplete billing profile links only verified Stripe metadata and does not grant a tier',async()=>{
  const path='/api/admin/recovery/billing/'+old+'/link-profile',body={reason:'Verified owned Stripe customer metadata after persistence failure',customerId:'cus_old',subscriptionId:'sub_old'};
  assert.equal((await request(path,body,user)).status,403);assert.equal((await request(path,body)).status,409);
  const previous=sub;sub={...sub,id:'sub_old',customer:'cus_old'};assert.equal((await request(path,body)).status,200);assert.equal((await request(path,body)).data.duplicate,true);assert.equal((await service.summary(old)).planId,'free');sub=previous;
 });
 await t.test('admin project-save recovery cannot submit pending audio and finalizes retained artifacts only',async()=>{
  const plan={projectName:'Retained result',bpm:120,totalBars:1,sigNum:4,sigDen:4,tracks:[{id:'voice',name:'Voice',mode:'audio',renderInstructions:'fixture'}]},source=sessionSource({plan,prompt:'fixture',lyrics:'fixture',requestKey:'finalization-recovery'});
  const r=await service.reserve(user,{quantity:1,requestKey:'finalization-recovery',source}),id=r.versions[0].id,execution={parts:{voice:{state:'ready',objectKey:'user-uploads/'+user+'/generations/Generation-'+id+'-voice.wav'},pending:{state:'queued'}},saved:false};
  await pool.query("UPDATE ysong_generation_versions SET state='failed',execution=$2 WHERE id=$1",[id,execution]);const path='/api/admin/recovery/generations/'+id+'/finalize',body={reason:'Retained artifact inspected after project storage failure'};
  assert.equal((await request(path,body)).status,409);delete execution.parts.pending;await pool.query('UPDATE ysong_generation_versions SET execution=$2 WHERE id=$1',[id,execution]);assert.equal((await request(path,body)).status,200);assert.equal((await request(path,body)).data.duplicate,true);
  let renders=0;const jobs=createSessionJobs({pool,service,enabled:()=>true,provider:()=>({provider:'cloudflare',model:'minimax/music-2.6'}),generate:async()=>{renders++;throw new Error('Must not render');},persist:async()=>{throw new Error('Must retain existing object');}});await jobs.tick();assert.equal(renders,0);assert.equal((await pool.query('SELECT state FROM ysong_generation_versions WHERE id=$1',[id])).rows[0].state,'ready');
 });
});
